complaint/auth.py
from flask import Blueprint, redirect, render_template, flash, request, session, url_for
from flask_login import login_required, logout_user, current_user, login_user
from flask import current_app as app
from werkzeug.security import generate_password_hash, check_password_hash
from .models import db, User
from . import login_manager

#Blueprint auth
auth =  Blueprint('auth_bp' , __name__)


@auth.route("/", methods=["GET", "POST"])
def login():

    """User login page."""

    # Bypass Login screen if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.form'))

    # POST: Create user and redirect them to the app
    if request.method == 'POST':
        data = request.form.to_dict()
        email, password = data.values()
        user = User.query.filter_by(email=email).first()
        if data:
            login_user(user, remember=False)
            next = request.args.get("next")
            return redirect(next or url_for("main_bp.form"))
        flash('Invalid username/password combination')

    # GET: Serve Log-in page
    return render_template("login.html")

@auth.route("/signup", methods=["GET", "POST"])
def signup():

    """User sign-up page."""

    # POST: Sign user in
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get("password")
        user_check = User.query.filter_by(email=email).first()
        if user_check is None:
            user = User(
                name=name,
                email=email,
                password=generate_password_hash(password)
            )
            db.session.add(user)
            db.session.commit()
            login_user(user)
            return redirect(url_for("main_bp.index"))

        flash('A user already exists with that email address.')
    # GET: Serve Sign-up page
    return render_template("signup.html")


@auth.route("/logout")
@login_required
def logout_page():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth_bp.login'))

@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None





#from flask import Flask, render_template, url_for, request, redirect, flash
#import requests
#import json
#import hashlib
#
#app = Flask(__name__)
#app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0
#app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'
#
#@app.errorhandler(404)
#def page_not_found(error):
#    return render_template('404.html'), 404
#
#@app.route('/', methods=['POST', 'GET'])
#def form():
#    if request.method == 'POST':
#        data =  request.form.to_dict()
#        request_api(data)
#        texts = get_complaints()
#        return redirect(url_for("form"))
#    return render_template("index.html", value=get_complaints())
#
#
#def request_api(data):
#    #data["category"] = [{"name":"Selling"}]
#    response = requests.post('https://complaint.microapi.dev/v1/complaint/new', headers={'Content-Type': 'application/json'}, data=json.dumps(data))
#    if response.status_code != 201:
#
#    ## flash is not working yet
#        flash('Please try again.')
#    else:
#        flash('Complaint has successfully being submitted!!')
#
#
#
#@app.route('/delete/<_id>', methods=['GET'])
#def delete(_id):
#    response = requests.delete('https://complaint.microapi.dev/v1/complaint/delete/'+str(_id), headers={'Content-Type': 'application/json'})
#    return redirect(url_for("form"))
#
#@app.route('/update/<_id>', methods=["POST"])
#def update(_id):
#    data = request.form.to_dict()
#    data["status"] =  "closed"
#    response = requests.patch('https://complaint.microapi.dev/v1/complaint/update/'+str(_id), headers={'Content-Type': 'application/json'}, data=json.dumps(data))
#    print(data, response.text)
#    return redirect(url_for("form"))
#
#
#def get_complaints():
#    response = requests.get('https://complaint.microapi.dev/v1/complaint/all')
#    all_complaints = response.json()
#    return all_complaints

complaint/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_assets import Environment, Bundle
from flask_login import current_user
from flask import current_app as app
from .models import User
from flask_login import login_required, current_user
import requests
import json
import hashlib

cid = ''
# app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'
main_bp = Blueprint('main_bp', __name__,
                    static_folder="static")


@main_bp.app_errorhandler((404))
def page_not_found(error):
    return render_template('404.html'), 404


@main_bp.route('/', methods=['POST', 'GET'])
def form():
    if request.method == 'POST':
        data = request.form.to_dict()
        request_api(data)
        texts = get_complaints()
        return redirect(url_for("main_bp.form"))
    return render_template("index.html", value=get_complaints())


def request_api(data):
    # data["category"] = [{"name":"Selling"}]
    response = requests.post('https://complaint-microapi.herokuapp.com/v1/complaint/new',
                             headers={'Content-Type': 'application/json'}, data=json.dumps(data))
    print(response.text)
    if response.status_code != 201:

        # flash is not working yet
        flash('Please try again.')
    else:
        flash('Complaint has successfully being submitted!!')
        return render_template("index.html", value=get_complaints())


@main_bp.route('/delete/<_id>', methods=['GET'])
def delete(_id):
    response = requests.delete('https://complaint-microapi.herokuapp.com/v1/complaint/delete' +
                               str(_id), headers={'Content-Type': 'application/json'})
    flash('Complaint Deleted!')
    return redirect(url_for("main_bp.form"))


@main_bp.route('/update/<_id>', methods=["POST"])
def update(_id):
    data = request.form.to_dict()
    data["status"] = "closed"
    response = requests.patch('https://complaint-microapi.herokuapp.com/v1/complaint/update'+str(
        _id), headers={'Content-Type': 'application/json'}, data=json.dumps(data))
    print(data, response.text)
    return redirect(url_for("main_bp.form"))


def get_complaints():
    response = requests.get(
        'https://complaint-microapi.herokuapp.com/v1/complaint/all')
    all_complaints = response.json()
    return all_complaints


@main_bp.route('/comments/<_id>', methods=['GET'])
def comments(_id):
    response = requests.get('https://complaint-microapi.herokuapp.com/v1/'+str(
        _id)+'/comment/all', headers={'Content-Type': 'application/json'})
    all_comments = response.json()
   # global cid
    cid = _id
    print(all_comments)
    return render_template("comments.html", value=all_comments)


@main_bp.route('/new_comment/<_id>', methods=['POST', 'GET'])
def new_comment(_id):
   # global cid
   # This is not working
    data = request.form.to_dict()
    response = requests.post('https://complaint-microapi.herokuapp.com/v1/'+str(
        _id)+'/comment/new', headers={'Content-Type': 'application/json'}, data=json.dumps(data))
    if response.status_code == 201:
        flash('Comment has successfully being submitted!!')
    else:
        flash('Please try again.')
    return redirect(url_for("main_bp.comments", _id=cid))

complaint/templates/comments.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>COMPLAINTS MANAGEMENT MICROSERVICE</title>
    <meta property="og:type" content="website">
    <meta property="og:description" content="COMPLAINTS MANAGEMENT MICROSERVICE">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{{url_for('main_bp.static', filename='comform/css/bootstrap.min.css')}}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- Google fonts - Popppins for copy-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round|Muli:200,400,800|Poppins|Lato|Playfair+Display" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One&display=swap" rel="stylesheet">
 
    <!-- <!-- orion icons-->
    <link rel="stylesheet" href="{{url_for('main_bp.static', filename='comform/css/orionicons.css')}}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{{url_for('main_bp.static', filename='comform/css/style.default.css')}}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{{url_for('main_bp.static', filename='comform/css/custom.css')}}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{{url_for('main_bp.static', filename='comform/image/logo-1.svg')}}"> -->
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <!-- navbar-->
    <header class="header">
      <nav class="navbar navbar-expand-lg shadow" >
        <a class="sidebar-toggler text-gray-500 mr-4 mr-lg-5 lead">
          <i class="fas fa-align-left" style="color:#c94b4b"></i>
        </a>
        <a class="navbar-brand font-weight-bold text-uppercase text-base" style="color:#c94b4b">
          <img src="{{url_for('main_bp.static', filename='comform/image/logo-1.svg')}}" style="width: 1rem;height: 1rem;">TEAM JUSTICE LEAGUE</a>
      </nav>
    </header>
    <div class="d-flex align-items-stretch" >
      <div id="sidebar" class="sidebar py-3">
        <div class="text-gray-400 text-uppercase px-3 px-lg-4 py-4 font-weight-bold small headings-font-family"><h5>MAIN</h5></div>
        <ul class="sidebar-menu list-unstyled">
          <li class="sidebar-list-item">
            <a href="#" class="sidebar-link text-black"><span>HOME</span>
            </a>
          </li>
        </ul>
      </div>
      <div class="page-holder w-100 d-flex flex-wrap">
        <div class="container-fluid px-xl-5" >
          <section class="py-5">
            <div class="row" >
              
              <!-- Form Elements -->
              <div class="col-lg-12 mb-5" >
                <div class="card">
                  <div class="card-header text-center">
                    <h3 class="h6 text-uppercase mb-0">COMPLAINTS MANAGEMENT MICROSERVICE TESTING</h3>
                  </div>
                  <div class="card-body">
                    {% block content %} {% for comments in value['result'] %}
                        <article class="post">
                          <p class="body">{{ comments["message"] }} <br>Date - <span class="text-muted">{{ comments["updated_at"][:-16] }}</span></p>
                        </article>  
                        {% if not loop.last %}
                          <hr>
                        {% endif %}
                      {% endfor %}
                    {% endblock %}
                    <br>
                    <br>
                  <div class="text-center">
                    <h5>Add Comments</h5>
                    <form action="{{ url_for('main_bp.new_comment', _id=['complaint_id']) }}" method="POST" class="p-3">
                        <div class="form-group">
                            <label for="message">Message</label>
                            <textarea class="form-control rounded-lg" placeholder="Enter your message" name="message" required></textarea>
                        </div>
                        <div class="form-group">       
                            <input type="submit" value="Add Comment" class="btn btn-primary">
                        </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
    <div class="copyright">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h4 class="h6 text-black">Made By Complaints MicroAPI Back-End Team</h4>
                </div> <!-- end of col -->
            </div> <!-- enf of row -->
        </div> <!-- end of container -->
    </div> <!-- end of copyright --> 
    <!-- JavaScript files--> 
    <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
    <script type="text/javascript" src="{{url_for('main_bp.static', filename='comform/js/scripts.js')}}"></script>
    <script src="{{url_for('main_bp.static', filename='comform/js/jquery.min.js')}}"></script>
    <script src="{{url_for('main_bp.static', filename='comform/js/complaint.js')}}"></script>
    <script src="{{url_for('main_bp.static', filename='comform/js/popper.js/umd/popper.min.js')}}"></script>
    <script src="{{url_for('main_bp.static', filename='comform/js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('main_bp.static', filename='comform/js/front.js')}}"></script>
  </body>
</html>

complaint/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>COMPLAINTS MANAGEMENT MICROSERVICE</title>
    <meta property="og:type" content="website">
    <meta property="og:description" content="COMPLAINTS MANAGEMENT MICROSERVICE">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="static/comform/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- Google fonts - Popppins for copy-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round|Muli:200,400,800|Poppins|Lato|Playfair+Display" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One&display=swap" rel="stylesheet">
 
    <!-- orion icons-->
    <link rel="stylesheet" href="static/comform/css/orionicons.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="static/comform/css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="static/comform/css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{{ url_for('static', filename='comform/image/logo-1.svg') }}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <!-- navbar-->
    <header class="header">
      <nav class="navbar navbar-expand-lg shadow" >
        <a class="sidebar-toggler text-gray-500 mr-4 mr-lg-5 lead">
          <i class="fas fa-align-left" style="color:#c94b4b"></i>
        </a>
        <a class="navbar-brand font-weight-bold text-uppercase text-base" style="color:#c94b4b">
          <img src="static/comform/image/logo-1.svg" style="width: 1rem;height: 1rem;">TEAM JUSTICE LEAGUE</a>
      </nav>
    </header>
    <div class="d-flex align-items-stretch" >
      <div id="sidebar" class="sidebar py-3">
        <div class="text-gray-400 text-uppercase px-3 px-lg-4 py-4 font-weight-bold small headings-font-family"><h5>MAIN</h5></div>
        <ul class="sidebar-menu list-unstyled">
          <li class="sidebar-list-item">
            <a href="#" class="sidebar-link text-black"><span>HOME</span>
            </a>
          </li>
        </ul>
      </div>
      <div class="page-holder w-100 d-flex flex-wrap">
        <div class="container-fluid px-xl-5" >
          <section class="py-5">
            <div class="row" >
              
              <!-- Form Elements -->
              <div class="col-lg-12 mb-5" >
                <div class="card">
                  <div class="card-header text-center">
                    <h3 class="h6 text-uppercase mb-0">COMPLAINTS MANAGEMENT MICROSERVICE TESTING</h3>
                  </div>
                  <div class="card-body">
                    {% block content %}
                      {% for complaint in value['result'] %}
                        <article class="post">
                          <div class="text-right">
                            <a href="{{ url_for('main_bp.delete', _id=complaint.id) }}">
                              <ion-icon style="color:blue"; name="trash-sharp"></ion-icon>
                            </a>
                             {% if complaint.status == "new" %}
                              <span class="h6 badge badge-primary">
                                {{ complaint.status  }}
                              </span> 
                            {% elif complaint.status == "closed" %}
                              <span class="h6 badge badge-danger">
                                {{ complaint.status  }}
                              </span> 
                            {% elif complaint.status == "resolved" %}
                              <span class="h6 badge badge-success">
                                {{ complaint.status  }}
                              </span>    
                            {% endif %}
                          </div>
                          <div>
                            <a href="{{ url_for('main_bp.comments', _id=complaint.id) }}" style="text-decoration: none;">
                              <h4>{{ complaint["title"] }}</h4>
                              <div class="about ">Date - <span class="text-muted">{{ complaint["updated_at"][:-16] }}</span></div>
                            </a>
                          </div>
                          <p class="body">{{ complaint["message"] }}</p>
                        </article>
                        {% if not loop.last %}
                          <hr>
                        {% endif %}
                      {% endfor %}
                    {% endblock %}
                    <br>
                    <br>
                    <button type="button" data-toggle="modal" data-target="#myModal" class="btn" style="text-align: center;background-color:#c94b4b;">Fill Out a Complaint Form</button>
                    <!-- Modal-->
                    <div id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" class="modal fade text-left">
                      <div role="document" class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h4 id="exampleModalLabel" class="modal-title">Fill Out a Complaint Form</h4>
                            <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                          </div>
                          <div class="modal-body">
                            <form  method="POST" autocomplete="off">
                              <div class="form-group">
                                <label class="h6 mb-0">Title </label>
                                <input type="text" name="title" placeholder="Title" class="form-control rounded-lg" required>
                              </div>
                              <div class="form-group">       
                                <label class="h6 mb-0">Message</label>
                                <textarea class="form-control rounded-lg " name="message" placeholder="Enter Your Message" required></textarea>
                              </div>
                              <div class="form-group">       
                                <label class="h6 mb-0">User ID</label>
                                <input type="number" name="user_id" placeholder="User Id" class="form-control rounded-lg " required>
                              </div>
                              {% for message in get_flashed_messages() %}
                                <div class="alert alert-warning">
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                              <div class="form-group">       
                                <input type="submit" value="Submit" class="btn btn-primary">
                              </div>
                            </form>
                          </div>
                          <div class="modal-footer">
                            <button type="button" data-dismiss="modal" class="btn btn-secondary">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
    <div class="copyright">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h4 class="h6 text-black">Made By Complaints MicroAPI Back-End Team</h4>
                </div> <!-- end of col -->
            </div> <!-- enf of row -->
        </div> <!-- end of container -->
    </div> <!-- end of copyright --> 
    <!-- JavaScript files--> 
    <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
    <script type="text/javascript" src="static/comform/js/scripts.js"></script>
    <script src="static/comform/js/jquery.min.js"></script>
    <script src="static/comform/js/complaint.js"></script>
    <script src="static/comform/js/popper.js/umd/popper.min.js"></script>
    <script src="static/comform/js/bootstrap.min.js"></script>
    <script src="static/comform/js/front.js"></script>
  </body>
</html>

complaint/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V2</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
<link rel="icon" type="image/png" href="{{ url_for('static',filename='login/images/icons/favicon.ico') }}"/>
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='login/vendor/bootstrap/css/bootstrap.min.css') }}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='login/fonts/font-awesome-4.7.0/css/font-awesome.min.css') }}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='login/fonts/iconic/css/material-design-iconic-font.min.css')}}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='login/vendor/animate/animate.css') }}">
<!--===============================================================================================-->	
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='login/vendor/css-hamburgers/hamburgers.min.css') }}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href=" {{ url_for('static',filename='login/vendor/animsition/css/animsition.min.css') }}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href=" {{ url_for('static',filename='login/vendor/select2/select2.min.css') }}">
<!--===============================================================================================-->	
<link rel="stylesheet" type="text/css" href=" {{ url_for('static',filename='login/vendor/daterangepicker/daterangepicker.css') }} ">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='login/css/util.css') }}">
    <link rel="stylesheet" type="text/css" href=" {{ url_for('static',filename='login/css/main.css') }}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="POST">
					<span class="login100-form-title p-b-26">
						Welcome
					</span>
					<span class="login100-form-title p-b-48">
						<i class="zmdi zmdi-font"></i>
					</span>
                    {% for message in get_flashed_messages() %}
                        <div class="alert alert-warning">
                             <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{ message }}
                    </div>
                    {% endfor  %}
					<div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
						<input class="input100" type="text" name="email">
						<span class="focus-input100" data-placeholder="Email"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="pass">
						<span class="focus-input100" data-placeholder="Password"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Login
							</button>
						</div>
					</div>

					<div class="text-center p-t-115">
						<span class="txt1">
							Don’t have an account?
						</span>

                        <a class="txt2" href="{{ url_for("auth_bp.signup") }} ">
							Sign Up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
    <script src="{{ url_for('static',filename='login/vendor/jquery/jquery-3.2.1.min.js') }}"></script>
<!--===============================================================================================-->
    <script src="{{ url_for('static',filename='login/vendor/animsition/js/animsition.min.js') }}"></script>
<!--===============================================================================================-->
    <script src="{{ url_for('static',filename='login/vendor/bootstrap/js/popper.js') }}"></script>
    <script src="{{ url_for('static',filename='login/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<!--===============================================================================================-->
    <script src="{{ url_for('static',filename='login/vendor/select2/select2.min.js') }}"></script>
<!--===============================================================================================-->
    <script src="{{ url_for('static',filename='login/vendor/daterangepicker/moment.min.js') }}"></script>
    <script src="{{ url_for('static',filename='login/vendor/daterangepicker/daterangepicker.js') }}"></script>
<!--===============================================================================================-->
    <script src="{{ url_for('static',filename='login/vendor/countdowntime/countdowntime.js') }}"></script>
<!--===============================================================================================-->
    <script src="{{ url_for('static',filename='login/js/main.js') }}"></script>

</body>
</html>